#!/usr/bin/env ruby

# prefix char for commands
$cmdChar = '!'
$animalActivityRate = 1.0

# loads and requires
require 'rubygems'
require 'socket'
require 'mysql'
load 'functions.rb'
load 'framework.rb'
load 'handler.rb'
load 'pastoralserver.rb'
load 'terminal.rb'
load 'direction.rb'
load 'user.rb'
load 'tcpsocket.rb'
load 'cube.rb'
load 'inventory.rb'
load 'item.rb'
load 'animal.rb'
load 'animals/bird.rb'
load 'animals/deer.rb'
load 'animals/pigeon.rb'
load 'animals/finch.rb'
load 'animals/seagull.rb'
load 'animals/wave.rb'
load 'animals/crab.rb'
load 'synonyms.rb'

$myDB = Mysql.real_connect("localhost", "root", "sthlkj12", "pastoral")
$myServer = PastoralServer.new('192.168.0.111',5151)

load 'loadAnimals.rb'

$myServer.go
